FROM astral/uv:python3.12-trixie

WORKDIR /app

RUN uv venv
RUN uv pip install --no-cache-dir psycopg2-binary
RUN uv pip install mlflow boto3

EXPOSE 5000

CMD ["uv", "run", "mlflow", "server", "--default-artifact-root", "./mlruns", "--host", "0.0.0.0", "--port", "5000"]
