source_paths: 
 - D:\PhD\Data per camp\Exported annotations and labels\Wet season - Rep 3

source_format: ls

root: D:/PhD/workspace/data

split_name: val

ls_xml_config: D:\PhD\workspace\wildata\configs\label_studio_config.xml
ls_parse_config: false
bbox_tolerance: 5
draw_original_bboxes: false
roi_config:
  random_roi_count: 1
  roi_box_size: 128
  min_roi_size: 32
  dark_threshold: 0.7
  background_class: "background"
  save_format: "jpg"
  quality: 95