# Census Campaign Configuration
# This file contains all parameters needed for the census command

# Campaign Configuration
campaign:
  id: "campaign_001"
  pilot_name: "Unknown"
  target_species: null  # List of target species for detection


# Detection Configuration (inherits from detection.yaml)
detection:

  # Include only one directory path or a list of image paths
  images: 
    - D:\workspace\data\savmap_dataset_v2\raw\tmp

  # Model Configuration
  model:
    path: null  # Will use WILDETECT_MODEL_PATH env var if null
    type: "yolo"  # yolo, ultralytics, etc.
    confidence_threshold: 0.2
    device: "auto"  # auto, cpu, cuda
    batch_size: 32
    nms_iou: 0.5
  
  # Processing Configuration
  processing:
    tile_size: 800
    overlap_ratio: 0.2
    pipeline_type: "single"  # single, multi
    queue_size: 64  # for multi-threaded pipeline
  
  # Flight Specifications
  flight_specs:
    sensor_height: 24.0  # mm
    focal_length: 35.0   # mm
    flight_height: 180.0  # meters
  
  # ROI Classifier Configuration
  roi_classifier:
    weights: null  # Will use ROI_MODEL_PATH env var if null
    feature_extractor_path: "facebook/dinov2-with-registers-small"
    cls_label_map:
      0: "groundtruth"
      1: "other"
    keep_classes: ["groundtruth"]
    cls_imgsz: 96  # Smaller for census processing
  
  # Inference Service Configuration
  inference_service:
    url: null  # URL for external inference service
  
  # Profiling Configuration
  profiling:
    enable: false
    memory_profile: false
    line_profile: false
    gpu_profile: false

# Export Configuration
export:
  to_fiftyone: true
  create_map: true
  output_directory: null  # Will use campaign_id if null
  export_to_labelstudio: true

# Logging Configuration
logging:
  verbose: false
  log_file: null  # Will use default log path if null
