# Detection Pipeline Configuration
# This file contains all parameters needed for the detection command

# Model Configuration
model:
  mlflow_model_name: "detector"
  mlflow_model_alias: "demo"
  device: "auto"  # auto, cpu, cuda

# Include only one directory path or a list of image paths
images: 
 - d:/workspace/data/savmap_dataset_v2/raw/tmp

# Processing Configuration
processing:
  batch_size: 8
  tile_size: 800
  overlap_ratio: 0.2
  pipeline_type: "single"  # single, multi, async
  queue_size: 64  # for multi-threaded pipeline
  num_workers: 4

# Flight Specifications
flight_specs:
  sensor_height: 24.0  # mm
  focal_length: 35.0   # mm
  flight_height: 180.0  # meters


# Inference Service Configuration
inference_service:
  url: http://localhost:4141/predict  # URL for external inference service
  timeout: 60

# Profiling Configuration
profiling:
  enable: false
  memory_profile: false
  line_profile: false
  gpu_profile: false

# Output Configuration
output:
  directory: "results"
  dataset_name: null  # if null, fiftyone dataset upload is disabled

# Logging Configuration
logging:
  verbose: false
  log_file: null  # Will use default log path if null
