# Detection Pipeline Configuration
# This file contains all parameters needed for the detection command

# Model Configuration
model:
  mlflow_model_name: "detector"
  mlflow_model_alias: "demo"
  device: "auto"  # auto, cpu, cuda

# Include only one directory path or a list of image paths
images: 
 - D:\workspace\data\savmap_dataset_v2\raw\tmp-1 # TODO: update

# Label Studio Configuration
labelstudio:
  url: "http://localhost:8080"
  api_key: null 
  project_id: null
  download_resources: false
  from_name: "label"
  to_name: "image"
  label_type: "rectanglelabels"

# Processing Configuration
processing:
  batch_size: 8
  tile_size: 800
  overlap_ratio: 0.2
  pipeline_type: "single"  # single, multi, async
  queue_size: 64  # for multi-threaded pipeline
  num_workers: 4

# Flight Specifications
flight_specs:
  sensor_height: 15.6  # mm
  focal_length: 16.0   # mm
  flight_height: 120.0  # meters


# Inference Service Configuration
inference_service:
  url: null #http://localhost:4141/predict  # URL for external inference service
  timeout: 60

# Profiling Configuration
profiling:
  enable: false
  memory_profile: false
  line_profile: false
  gpu_profile: false

# Output Configuration
output:
  directory: "results"
  dataset_name: null  # if null, fiftyone dataset upload is disabled

# Logging Configuration
logging:
  verbose: false
  log_file: null  # Will use default log path if null
