# Visualization Configuration
# This file contains all parameters needed for visualization commands

labelstudio:
  url: http://localhost:8080
  api_key: null # <<< TO change HERE
  download_resources: false
  project_id: null
  json_path: null  # <<< TO change HERE
  dotenv_path: .env
  parse_ls_config: true
  ls_xml_config: null


csv_output_path: D:\PhD\Harvard Kruger River Surveys\20231017_LetabaRiver_BasaltA\annotations\detections_v2.csv
detection_type: "annotations" # annotations, predictions


# Flight Specifications
flight_specs:
  sensor_height: 15.6  # mm
  focal_length: 16.0   # mm
  flight_height: 120.0  # meters

# Logging Configuration
logging:
  verbose: false
  log_file: null  # Will use default log path if null
