# Visualization Configuration
# This file contains all parameters needed for visualization commands
# Extract GPS coordinates for detections in Label Studio

# set project_id or json_path
labelstudio:
  url: http://localhost:8080
  api_key: 4f3c25bad9334596c5b2c3b270a2d3105c8b5d4a # <<< TO change HERE
  download_resources: false
  project_id: 44 # <<< TO change HERE (1)
  json_path: null #C:\Users\Machine Learning\Downloads\project-200-at-2026-02-23-10-54-8dced6cd.json # <<< OR change HERE (2)
  dotenv_path: .env
  parse_ls_config: true
  ls_xml_config: null

exif_gps_update:
  image_folder: D:\PhD\Data per camp\Wet season\Leopard rock\Camp 23-28\Rep 1 - tiled # Path to folder containing images
  csv_path: D:\PhD\Data per camp\Wet season\Leopard rock\Camp 23-28\Rep 1-coordinates.csv  # Path to CSV file with GPS coordinates
  skip_rows: null  # null or Number of rows to skip in CSV (e.g., header row)
  delimiter: ","
  filename_col: "filename"  # CSV column name for filenames
  lat_col: "latitude"  # CSV column name for latitude
  lon_col: "longitude"  # CSV column name for longitude
  alt_col: "altitude"  # CSV column name for altitude

csv_output_path: leopard-rock-wet_season-camp23_28-Rep1
detection_type: "annotations" # annotations, predictions


# Flight Specifications
flight_specs:
  sensor_height: 15.6  # mm
  focal_length: 16.0   # mm
  flight_height: 120.0  # meters

# Logging Configuration
logging:
  verbose: false
  log_file: null  # Will use default log path if null
