# Visualization Configuration
# This file contains all parameters needed for visualization commands

labelstudio:
  url: http://localhost:8080
  api_key: 4f3c25bad9334596c5b2c3b270a2d3105c8b5d4a
  download_resources: false
  project_id: null
  json_path: "D:/PhD/Data per camp/Exported annotations and labels/April 25-July25/train/110 FiftyOne_campaign_LR_Farm_north.json"
  dotenv_path: .env
  parse_ls_config: true
  ls_xml_config: null


image_dir: null
csv_output_path: "detection_report.csv"
detection_type: "annotations" # annotations, predictions


# Flight Specifications
flight_specs:
  sensor_height: 15.6  # mm
  focal_length: 16.0   # mm
  flight_height: 120.0  # meters

# Logging Configuration
logging:
  verbose: false
  log_file: null  # Will use default log path if null
