# Visualization Configuration
# This file contains all parameters needed for visualization commands

labelstudio:
  url: "http://127.0.0.1:8080"
  api_key: "4f3c25bad9334596c5b2c3b270a2d3105c8b5d4a"
  download_resources: false
  project_id: 138


image_dir: null
csv_output_path: D:\PhD\Harvard Kruger River Surveys\20231017_LetabaRiver_BasaltA\annotations\detections.csv
detection_type: "annotations" # annotations, predictions

# Geographic Visualization of predictions
geographic:
  create_map: false
  show_confidence: false
  output_directory: "visualizations"
  map_type: "OpenStreetMap"  # OpenStreetMap, folium, etc.
  zoom_level: 12
  center_on_data: true

# Flight Specifications
flight_specs:
  sensor_height: 15.6  # mm
  focal_length: 16.0   # mm
  flight_height: 120.0  # meters

# Visualization Options
visualization:
  show_detections: true
  show_footprints: true
  show_statistics: true
  color_by_confidence: false
  confidence_threshold: 0.2

# Output Configuration
output:
  format: "html"  # html, png, pdf
  include_legend: true
  include_statistics: true
  auto_open: false  # Open in browser automatically

# Logging Configuration
logging:
  verbose: false
  log_file: null  # Will use default log path if null
